name: Nightly Release (Linux x64) (Self-Contained)

on:
  schedule:
    - cron: '15 7 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish Self-Contained
      run: dotnet publish MHServerEmu.sln --configuration Release --runtime linux-x64 --self-contained
    - name: Get current date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MHServerEmu-nightly-${{ env.DATE }}-Release-linux-x64-self-contained
        path: |
          ./src/MHServerEmu/bin/x64/Release/net8.0/linux-x64/publish
          !./src/MHServerEmu/bin/x64/Release/net8.0/linux-x64/publish/*.pdb
          !./src/MHServerEmu/bin/x64/Release/net8.0/linux-x64/publish/*.xml
